name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Run Tests
      run: php artisan test

    - name: Deploy to FTP
      run: |
        lftp -e "
          set ftp:ssl-allow no;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror -R -e -x .git/ --verbose ./api.furnixfurniture.co.id/;
          bye
        "
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_PATH: '/api.furnixfurniture.co.id/'
